azure:
  storage:
    account-name: devstoreaccount1
    account-key: ${AZURERITE_ACCOUNT_KEY}
    endpoint: http://127.0.0.1:10000/devstoreaccount1

spring:
  elasticsearch:
    uris: http://localhost:9200
  ai:
    azure:
      openai:
        api-key: ${AZURE_OPENAI_KEY}
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        embedding:
          deployment-name: text-embedding-ada-002