azure:
  storage:
    account-name: devstoreaccount1
    account-key: ${AZURERITE_ACCOUNT_KEY}
    endpoint: http://127.0.0.1:10000/devstoreaccount1

spring:
  data:
    elasticsearch:
      uris: http://localhost:9200